name: 'dartlang'
version: 0.0.1
description: An absolute bare-bones web app.
author: tomucha <tomucha@gmail.com>
homepage: https://www.dartlang.cz

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  fnx_ui:
    git:
      url: https://github.com/fnx-io/fnx_ui
      ref: master
      
dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter
